### ISSUE TITLE
Value cannot be null. Parameter name: config

### ISSUE THREAD

**Issue by AdamvvYau** [billyang/SurgingDemo#7]
运行Bill.Demo.Services.Server时，在ServiceHostBuilderExtensions.UseLog4net报错：
Value cannot be null.
Parameter name: config  
 at Microsoft.Extensions.Options.ConfigurationChangeTokenSource`1..ctor(String name, IConfiguration config)
   at Microsoft.Extensions.Logging.LoggingBuilderExtensions.AddConfiguration(ILoggingBuilder builder, IConfiguration configuration)
   at Surging.Core.Log4net.ServiceHostBuilderExtensions.<>c.<UseLog4net>b__0_0(ILoggingBuilder logger) in D:\microservice\surging\src\Surging.Core\Surging.Core.Log4net\ServiceHostBuilderExtensions.cs:line 15
   at Microsoft.Extensions.DependencyInjection.LoggingServiceCollectionExtensions.AddLogging(IServiceCollection services, Action`1 configure)
   at Surging.Core.ServiceHosting.Internal.Implementation.ServiceHostBuilder.Build() in D:\microservice\surging\src\Surging.Core\Surging.Core.ServiceHosting\Internal\Implementation\ServiceHostBuilder.cs:line 34
   at Bill.Demo.Services.Server.Program.Main(String[] args) in D:\microservice\SurgingDemo\src\Bill.Demo.Solutions\Bill.Demo.Services.Server\Program.cs:line 24

我发现这个问题是在host.Build()的时候调用了
                })
                .UseStartup<Startup>()
                .Build();

            using (host.Run())
            {
                Console.WriteLine($"服务端启动成功，{DateTime.Now}。");
            }
但是这个Configuration是在host.Run()初始化的。
而host.Run()在Build()后执行，所以报了个null的错误。

作者方便解答下这个该怎么解决吗？

**Comment by doscanner** [comment]
这个问题解决了吗
